Feature/weather app
bruhGrassi/WeatherApp pull request #1
Opened 2024-07-18 01:50 UTC by bruhGrassi

2024-07-19 02:52 UTC, willianjusten commented on README.md
It would be nice to have an `.env.example` with just the name of the key and also an explanation in the Readme, explaining how to add the key and how to run the project.

2024-07-19 02:54 UTC, willianjusten commented on src/App.jsx
> +    fetchWeather,
Instead of passing a `fetchWeather` and then use 2 fetchs to different places, let's use the `fetchWeatherForLocation`, which will be a combined fetch for both current and forecast.

```suggestion
    fetchWeatherForLocation,
```

2024-07-19 03:18 UTC, willianjusten commented on src/App.jsx
> +  };
For here, you're using 2 fetchs, one first and then another, let's use the new one that will aggregate both.
Also, instead of `isSuccessful`, let's use `isValidLocation`, so it makes a bit more sense, since you want to add locations only when valid.

Also, prefer to use `prevLocations` to be clear you're merging with the previous ones. Also, you can use more use of the ternary to return one or another, saving `return` and `if`

```suggestion
const handleLocationSearch = async (location) => {
  const isValidLocation = await fetchWeatherForLocation(location);
  
  if (isValidLocation && typeof location === "string") {
    setLocations((prevLocations) =>
      !prevLocations.includes(location)
        ? [...prevLocations, location]
        : prevLocations
    );
    
    handleLocationSearchVisibility();
  }
};
```

2024-07-19 03:20 UTC, willianjusten commented on src/App.jsx
> +                handleOnClick={handleCurrentLocationPosition}
As I said to you, we usually use `handleOnClick` when it's clear what's being clicked, like a single only button, but the today weather has 2 buttons, so can be a bit confusing, so let's use:

```suggestion
                handleOnGeolocationClick={handleCurrentLocationPosition}
```

2024-07-19 03:21 UTC, willianjusten commented on src/assets/icons/close.png
It's fine to use png, but I'd prefer to always use SVG. You could even import from a library like:
https://fontawesome.com/

2024-07-19 03:21 UTC, willianjusten commented on src/assets/images/nublado.png
Everything was in english, than it comes "nublado" hahaha

2024-07-19 03:23 UTC, willianjusten commented on src/components/ErrorMessage/ErrorMessage.jsx
> +  return <p className="error-message">{error}</p>;
What happens if you pass an empty string, the `p` tag would appear anyway, so it's better to do something like:

```suggestion
  return error ? <p className="error-message">{error}</p> : null;
```

2024-07-19 03:51 UTC, willianjusten commented on src/App.jsx
> +    <>
You already have 1 parent `container`, there's no need to use Fragment here.

2024-07-19 03:54 UTC, willianjusten commented on src/components/HighlightCard/HighlightCard.jsx
> +        </div>
Don't worry about this, but you should actually point the correct wind direction of the wind based on the `wind.deg` value, rotating the arrow with `transform: rotate`. Also this "WSW" should mean the direction, like "NE" Northeast, etc...

Again, don't need to do that okay, it's fine already.

2024-07-19 03:55 UTC, willianjusten commented on src/App.jsx
> +  };
There's no need to have this method, just call the `handleLocationSearch`, it does exactly the same thing.

```suggestion
```

2024-07-19 03:56 UTC, willianjusten commented on src/App.jsx
> +                handleListSearch={handleListSearch}
Just delete this method and use the other one `handleLocationSearch`

2024-07-19 03:56 UTC, willianjusten commented on src/components/LocationSearch/LocationSearch.jsx
> +  handleListSearch,
Remove this one
```suggestion
```

2024-07-19 03:57 UTC, willianjusten commented on src/components/LocationSearch/LocationSearch.jsx
> +  handleLocationSearch,
Also, I like to put the handles always in the end, like:

```suggestion
  error,
  locations,
  isLocationSearchOpen,
  handleLocationSearch,
  handleLocationSearchVisibility
```

2024-07-19 03:57 UTC, willianjusten commented on src/components/LocationSearch/LocationSearch.jsx
> +            handleLocation={() => handleListSearch(location)}
```suggestion
            handleLocation={() => handleLocationSearch(location)}
```

2024-07-19 03:57 UTC, willianjusten commented on src/components/LocationSearch/LocationSearch.jsx
> +  setLocations: PropTypes.func,
You're not using this anymore, can remove it.
```suggestion
```

2024-07-19 03:58 UTC, willianjusten commented on src/components/LocationSearch/LocationSearch.jsx
> +  handleListSearch: PropTypes.func,
Can remove it.

```suggestion
```

2024-07-19 03:58 UTC, willianjusten commented on src/components/Locationitem/LocationItem.jsx
> +const LocationItem = ({ handleLocation, text }) => {
very nitpick, but as I said, prefer to put values first and methods after:

```suggestion
const LocationItem = ({ text, handleLocation }) => {
```

2024-07-19 03:59 UTC, willianjusten commented on src/components/RoundButton/RoundButton.jsx
> +const RoundButton = ({ onClick, children, variant, isActive }) => {
Methods at the end and values first:

```suggestion
const RoundButton = ({ children, variant, isActive, onClick }) => {
```

2024-07-19 04:00 UTC, willianjusten commented on src/components/TodayWeather/TodayWeather.jsx
> +  handleOnClick,
Values first, methods in the end:

```suggestion
  cityName,
  temperature,
  description,
  image,
  unit,
  handleLocationSearchVisibility,
  handleGeolocationClick,
```

2024-07-19 04:00 UTC, willianjusten commented on src/components/TodayWeather/TodayWeather.jsx
> +  handleOnClick: PropTypes.func,
Don't forget to change in the props as well.

2024-07-19 04:02 UTC, willianjusten commented on src/components/WeatherCard/WeatherCard.jsx
> +};
You're repeating the same comparison, would be better to create a variable and reuse:

```suggestion
const WeatherCard = ({ date, min_temp, max_temp, image, unit }) => {
  const iconUrl = `${ICON_URL}${image}@4x.png`;
  const currentUnit = unit === UNITS.CELSIUS ? UNITS.CELSIUS : UNITS.FAHRENHEIT;
  
  return (
    <div className="weather-card">
      <div className="weather-card__date">{date}</div>
      <img src={iconUrl} className="weather-card__image" />
      <div className="weather-card__temperature">
        <div className="weather-card__temperature--max">
          {max_temp}°{" "}
          {currentUnit}
        </div>
        <div className="weather-card__temperature--min">
          {min_temp}°{" "}
          {currentUnit}
        </div>
      </div>
    </div>
  );
};
```

2024-07-19 04:02 UTC, willianjusten commented on src/config.js
> +export const API_KEY = import.meta.env.VITE_API_KEY;
Why not having this one inside constants?

2024-07-19 04:05 UTC, willianjusten commented on src/hooks/useFetchWeather.js
> +  };
Tip 1: Remember what I said about let and reassigning variables? Always when you see that, try to avoid, because it's a code smell.

Tip 2: try to avoid very nested if/else if/else.

Tip 3: you don't need to pass `apiKey` as parameter, because it will be always the same constant.

Tip 4: sometimes if it's one or another, you just need to do the first comparison, so I created a helper variable to create the locationQuery and this simplified even more my url, being easier to read.

```suggestion
  const buildWeatherUrl = (location, type) => {
    const baseEndpoint =
      type === WEATHER_TYPES.CURRENT ? API.CURRENT_URL : API.FORECAST_URL;
    const locationQuery =
      typeof location === "string"
        ? `q=${location}`
        : `lat=${location.lat}&lon=${location.lon}`;
    return `${baseEndpoint}?${locationQuery}&appid=${API_KEY}&units=metric`;
  };
```

2024-07-19 04:14 UTC, willianjusten commented on src/hooks/useFetchWeather.js
> +  };
Tip 1: notice that you compare `type === WEATHER_TYPES.CURRENT` twice, so you could merge both cases.

Tip 2: you're already cathing the error, so there's no need to `console.error` in this case, only if you want to send this info to a developer dashboard like Sentry, but that's not the case.

I'm also moving the loading to bellow, because we'll aggregate them and use only the other fetch everywhere, having this one only as internal.

```suggestion
const fetchWeatherData = async (location, type) => {
  try {
    const url = buildWeatherUrl(location, type);
    
    const response = await fetch(url);
    if (!response.ok) throw new Error("City not found");

    const data = await response.json();

    if (type === WEATHER_TYPES.CURRENT) {
      setCurrentWeatherData(mapCurrentWeatherData(data))
    } else {
      setForecastWeatherData(mapForecastData(data));
    }
    
    return true;
  } catch (err) {
    setError(err.message);
    return false;
  }
};
```

2024-07-19 04:26 UTC, willianjusten commented on src/hooks/useFetchWeather.js
> +  };
When you write `await` you're telling the rest of the code "wait" until this line finishes. So in this case, you're first fetching the current and only after the current is fetched, you're fetching the forecast, this makes the app slower without necessity, because you can query both at the same time, in order to do that, you can use `Promise.all`.

Notice that I'm setting error as `null`, which is better than empty string and the loading is here.

I'm using [every](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every), just to return true/false so in your handleLocationSearch it knows if `isValidLocation` (success) or not.

Our results will be an array with 2 objects inside right? But if it errors, would return `[undefined, undefined]`, so the every in this case would return `false` for us. I know, this is a bit more tricky, but does the job.

Another thing, since you're using this method inside the `useEffect` bellow, you need to wrap into a `useCallback` so it memoizes the method and doesn't get recreated each render. (Don't worry, we'll get there, but this is nice to fix already)

```suggestion
  const fetchWeatherForLocation = useCallback(async (location) => {
    setError(null);
    setIsLoading(true);

    const results = await Promise.all([
      fetchWeatherData(location, WEATHER_TYPES.CURRENT),
      fetchWeatherData(location, WEATHER_TYPES.FORECAST),
    ]);

    setIsLoading(false);
    return results.every((result) => result); 
  }, []);
```

2024-07-19 04:27 UTC, willianjusten commented on src/hooks/useFetchWeather.js
> +  }, []);
You have to pass the dependencies inside the array, if not, react/eslint will complain
```suggestion
  }, [fetchWeatherForLocation, initialLocation]);
```

2024-07-19 04:27 UTC, willianjusten commented on src/hooks/useFetchWeather.js
> +    fetchWeather,
Now you return only the other fetch
```suggestion
    fetchWeatherForLocation,
```

2024-07-19 04:35 UTC, willianjusten requested changes
Looking great already, but let's push more!

2024-07-19 04:56 UTC, willianjusten commented on src/hooks/useFetchWeather.js
> +  const [currentWeatherData, setCurrentWeatherData] = useState({});
Prefer to use null instead of empty object for those cases (when working with TS you're going to thank me)
```suggestion
  const [currentWeatherData, setCurrentWeatherData] = useState(null);
```

2024-07-19 05:02 UTC, willianjusten commented on src/hooks/useFetchWeather.js
> +  };
Tip: when you have 2 returns like that with if, you can return directly and make the comparison to one or another with ternary.

```suggestion
const handleTemperatureUnit = (tempInCelsius, unit) => {
  return unit === UNITS.CELSIUS
    ? Math.trunc(tempInCelsius)
    : Math.trunc((tempInCelsius * 9) / 5 + 32);
  };
```

2024-07-19 18:11 UTC, bruhGrassi commented on src/components/HighlightCard/HighlightCard.jsx
> +        </div>
Yeah! I had thought about doing it later, but okay :)

2024-07-19 18:33 UTC, bruhGrassi commented on src/config.js
> +export const API_KEY = import.meta.env.VITE_API_KEY;
I wasn't sure if I should put it in that file or not, but it makes more sense...

2024-07-19 20:28 UTC, bruhGrassi commented on src/hooks/useFetchWeather.js
> +  const [currentWeatherData, setCurrentWeatherData] = useState({});
Only with empty objects? Is it okay with empty arrays?

2024-07-23 16:22 UTC, willianjusten approved these changes
Nice =)

2024-07-23 17:59 UTC, merged